# -*- coding: utf-8 -*-
"""Jersey YOLOv5-Custom-Training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JWymx1y3KYt3G0YBC1qUG2hrGD6-ug_N

# Step 1: Install Requirements
"""

# Commented out IPython magic to ensure Python compatibility.
#clone YOLOv5 and 
# %cd /content
!git clone https://github.com/ultralytics/yolov5  # clone repo
# %cd yolov5
# %pip install -qr requirements.txt # install dependencies
#%pip install  requirements.txt # install dependencies
# %pip install -q roboflow

import torch
import os
from IPython.display import Image, clear_output  # to display images

print(f"Setup complete. Using torch {torch.__version__} ({torch.cuda.get_device_properties(0).name if torch.cuda.is_available() else 'CPU'})")

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

!unzip "/content/drive/MyDrive/Jersey_new.zip" -d "/content/drive/MyDrive/Jersey_new"

# set up environment    /content/drive/MyDrive/Jersey.zip
os.environ["DATASET_DIRECTORY"] = "/content/drive/MyDrive/"

class data:
   def __init__(self):
     self.location = "/content/drive/MyDrive/Jersey_new/Jersey_new" # chnage this to your dataset path on google drive

# Commented out IPython magic to ensure Python compatibility.
# %cat /content/drive/MyDrive/Jersey_new/Jersey_new/data.yaml

dataset = data()

!python train.py --img 416 --batch 16 --epochs 500 --data {dataset.location}/data.yaml --weights yolov5s.pt --cache

# Commented out IPython magic to ensure Python compatibility.
# Start tensorboard
# Launch after you have started training
# logs save in the folder "runs"
# %load_ext tensorboard
# %tensorboard --logdir runs

"""#Run Inference  With Trained Weights
Run inference with a pretrained checkpoint on contents of `test/images` folder downloaded from Roboflow.
"""

!python detect.py --weights /content/yolov5/runs/train/exp3/weights/best.pt --img 416 --conf 0.1 --source {dataset.location}/test/images

#display inference on ALL test images

import glob
from IPython.display import Image, display

for imageName in glob.glob('/content/yolov5/runs/detect/exp/*.jpeg'): #assuming JPG
    display(Image(filename=imageName))
    print("\n")

#export your model's weights for future use
from google.colab import files
files.download('/content/yolov5/runs/train/exp3/weights/best.pt')